version: '3'
services:

  angular:
    container_name: angular
    build: client/
    ports: 
      - ${CLIENT_PORT}
    depends_on:
      - apollo
    networks:
      - bridge_net


  apollo:
    container_name: apollo
    build: graphql/
    depends_on:
    networks:
      - bridge_net
    ports: 
      - ${APOLLO_PORT}
    restart: always

networks:
  bridge_net: