# Dependencies Stage 
FROM node:latest AS deps

WORKDIR /deps
COPY package.json ./

RUN npm install


# Build Stage
FROM node:lts-bullseye
WORKDIR /app
COPY . .
#RUN npm install
COPY --from=deps /deps/node_modules ./node_modules
COPY --from=deps /deps/package-lock.json ./

CMD npm start
